add_newline=false

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"


[docker_context]
format = "via [🐋 $context](blue bold)"

[[battery.display]]
threshold = 20
style = "bold blue"

[lua]
symbol = "[](bold yellow)"

[python]
symbol = "[ ](bold #64648c)"
style = "bold #64648c"
